"use client";

import { useEffect, useState } from "react";
import { offlineFetch } from "../lib/offline/offlineFetch.js";

const RATING_BUTTONS = [
  { key: "again", label: "Again", hint: "didn't recall it" },
  { key: "good", label: "Good", hint: "recalled it" },
  { key: "easy", label: "Easy", hint: "trivial" },
];

// Spaced-repetition review of flashcards derived from content already
// generated by Teach/Grasp (see lib/adaptive/flashcards.js) -- nothing here
// is freshly AI-generated. Simplified SM-2 (lib/adaptive/srs.js) decides
// when each card comes back.
export default function FlashcardSession() {
  const [cards, setCards] = useState(null);
  const [error, setError] = useState(null);
  const [totalDue, setTotalDue] = useState(0);
  const [index, setIndex] = useState(0);
  const [revealed, setRevealed] = useState(false);
  const [rating, setRating] = useState(false);
  const [done, setDone] = useState(false);

  useEffect(() => {
    fetch("/api/flashcards")
      .then((r) => r.json())
      .then((data) => {
        if (data.error) setError(data.error);
        else {
          setCards(data.cards);
          setTotalDue(data.totalDue ?? data.cards.length);
        }
      })
      .catch((e) => setError(e.message));
  }, []);

  function rate(quality) {
    const card = cards[index];
    setRating(true);
    offlineFetch("/api/flashcards", { cardId: card.id, subtopicId: card.subtopicId, quality })
      .then(() => {
        setRevealed(false);
        if (index + 1 >= cards.length) setDone(true);
        else setIndex((i) => i + 1);
      })
      .catch(() => {})
      .finally(() => setRating(false));
  }

  if (error === "onboarding_not_complete") {
    return (
      <div className="card">
        <p className="lede" style={{ marginBottom: 10 }}>
          Set up your plan first — pick your 2 starting GS papers and your optional subject.
        </p>
        <a className="btn btn-primary" href="/onboarding">
          Get started →
        </a>
      </div>
    );
  }

  if (error) return <div className="error-box">{error}</div>;
  if (!cards) return <div className="loading">Loading…</div>;

  if (cards.length === 0) {
    return (
      <div className="card">
        <p className="lede" style={{ marginBottom: 0 }}>
          No cards due right now. Cards are built from key points, provisions, and mnemonics you've already
          generated by visiting Teach/Grasp on a topic — visit a few topics, then check back here.
        </p>
      </div>
    );
  }

  if (done) {
    return (
      <div className="card">
        <h2 style={{ marginTop: 0 }}>Session complete</h2>
        <p className="lede" style={{ marginBottom: 10 }}>
          Reviewed {cards.length} card{cards.length === 1 ? "" : "s"}
          {totalDue > cards.length ? ` (${totalDue - cards.length} more were due — come back for another round)` : ""}.
        </p>
        <a className="btn btn-primary" href="/flashcards">
          Refresh →
        </a>
      </div>
    );
  }

  const card = cards[index];

  return (
    <div className="card">
      <div className="meta-line">
        Card {index + 1} of {cards.length} · {card.subtopicText}
      </div>

      <div className="question-text">{card.front}</div>

      {!revealed ? (
        <button className="btn btn-primary" style={{ marginTop: 12 }} onClick={() => setRevealed(true)}>
          Show answer
        </button>
      ) : (
        <>
          <p style={{ fontSize: 14.5, marginTop: 12, padding: "10px 14px", background: "var(--ivory-2)", borderRadius: 8 }}>{card.back}</p>
          <div style={{ display: "flex", gap: 8, marginTop: 12 }}>
            {RATING_BUTTONS.map((b) => (
              <button key={b.key} className="btn" onClick={() => rate(b.key)} disabled={rating} title={b.hint}>
                {b.label}
              </button>
            ))}
          </div>
        </>
      )}
    </div>
  );
}
