// db/seed/legal-forums.js
//
// Starter catalog for legalForums (db/schema.js) -- common forum/court TYPES
// in the Indian legal/administrative system, modeled generically (not a
// directory of every physical bench/branch, which varies by state/district
// and changes over time). Pecuniary limits below reflect commonly-cited,
// generally-applicable figures (e.g. Consumer Protection Act 2019's July
// 2020 notification for the consumer commissions) but several vary by state
// amendment or later notification -- every row's `notes` says so explicitly,
// and lib/legal/forumRecommend.js's output is always framed as a starting
// point for the user to verify, never a final answer. Extend this list the
// same way db/seed/sources.js is extended: add a row, re-run the seed step.

export const legalForumsSeed = [
  {
    name: "Civil Court (Junior Division)",
    forumType: "civil_court",
    level: "local",
    description: "First-instance civil court for smaller-value civil disputes -- money recovery, contract, small property matters.",
    pecuniaryMin: null,
    pecuniaryMax: null,
    subjectTags: ["civil", "money recovery", "contract", "property", "damages"],
    caseTypeTags: ["civil"],
    appealsTo: "Civil Court (Senior Division) / District Judge",
    notes: "Pecuniary jurisdiction limits are set by each state government and vary widely -- verify the current limit in your district.",
  },
  {
    name: "Civil Court (Senior Division) / District Judge",
    forumType: "civil_court",
    level: "district",
    description: "Civil court for higher-value civil disputes, and first appellate court for Junior Division decrees.",
    pecuniaryMin: null,
    pecuniaryMax: null,
    subjectTags: ["civil", "money recovery", "contract", "property", "damages", "partition", "specific performance"],
    caseTypeTags: ["civil"],
    appealsTo: "High Court",
    notes: "Pecuniary jurisdiction limits are set by each state government and vary widely -- verify the current limit in your district.",
  },
  {
    name: "Judicial Magistrate (First Class)",
    forumType: "criminal_court",
    level: "local",
    description: "First-instance criminal court for most cognizable/non-cognizable offences short of the most serious ones.",
    pecuniaryMin: null,
    pecuniaryMax: null,
    subjectTags: ["criminal", "fir", "complaint", "cheque bounce", "criminal complaint"],
    caseTypeTags: ["criminal"],
    appealsTo: "Sessions Court",
    notes: "Sentencing powers are capped by law (typically up to 3 years' imprisonment) -- more serious offences are tried directly by Sessions Court.",
  },
  {
    name: "Sessions Court",
    forumType: "criminal_court",
    level: "district",
    description: "Tries serious criminal offences (e.g. carrying sentences above what a Magistrate can award) and hears appeals from Magistrate courts.",
    pecuniaryMin: null,
    pecuniaryMax: null,
    subjectTags: ["criminal", "serious offence", "appeal", "bail"],
    caseTypeTags: ["criminal"],
    appealsTo: "High Court",
    notes: "",
  },
  {
    name: "District Consumer Disputes Redressal Commission",
    forumType: "consumer_forum",
    level: "district",
    description: "First-instance forum for consumer complaints about defective goods, deficient services, or unfair trade practices.",
    pecuniaryMin: 0,
    pecuniaryMax: 10000000,
    subjectTags: ["consumer", "goods", "service", "deficiency", "unfair trade practice", "product defect", "warranty"],
    caseTypeTags: ["consumer"],
    appealsTo: "State Consumer Disputes Redressal Commission",
    notes: "Limit reflects the Consumer Protection Act 2019's July 2020 notification (value of goods/services paid up to ₹1 crore) -- verify the current limit before filing.",
  },
  {
    name: "State Consumer Disputes Redressal Commission",
    forumType: "consumer_forum",
    level: "state",
    description: "Appeals from District Commissions, and first-instance forum for higher-value consumer complaints.",
    pecuniaryMin: 10000000,
    pecuniaryMax: 100000000,
    subjectTags: ["consumer", "goods", "service", "deficiency", "unfair trade practice", "appeal"],
    caseTypeTags: ["consumer"],
    appealsTo: "National Consumer Disputes Redressal Commission",
    notes: "Limit reflects the Consumer Protection Act 2019's July 2020 notification (above ₹1 crore up to ₹10 crore) -- verify the current limit before filing.",
  },
  {
    name: "National Consumer Disputes Redressal Commission",
    forumType: "consumer_forum",
    level: "national",
    description: "Appeals from State Commissions, and first-instance forum for the highest-value consumer complaints.",
    pecuniaryMin: 100000000,
    pecuniaryMax: null,
    subjectTags: ["consumer", "goods", "service", "deficiency", "unfair trade practice", "appeal"],
    caseTypeTags: ["consumer"],
    appealsTo: "Supreme Court of India",
    notes: "Limit reflects the Consumer Protection Act 2019's July 2020 notification (above ₹10 crore) -- verify the current limit before filing.",
  },
  {
    name: "Family Court",
    forumType: "family_court",
    level: "district",
    description: "Matrimonial and family disputes -- divorce, judicial separation, maintenance, custody, guardianship.",
    pecuniaryMin: null,
    pecuniaryMax: null,
    subjectTags: ["divorce", "maintenance", "custody", "matrimonial", "guardianship", "alimony"],
    caseTypeTags: ["family"],
    appealsTo: "High Court",
    notes: "Not every district has a dedicated Family Court -- where absent, a designated Civil Court exercises this jurisdiction instead.",
  },
  {
    name: "Labour Court",
    forumType: "labour_court",
    level: "district",
    description: "Individual employment disputes -- wrongful dismissal, wage disputes, service conditions for workmen.",
    pecuniaryMin: null,
    pecuniaryMax: null,
    subjectTags: ["wages", "termination", "dismissal", "employment", "workman", "reinstatement"],
    caseTypeTags: ["labour"],
    appealsTo: "High Court",
    notes: "A labour dispute usually must first be raised via conciliation with the Labour Department before it can be referred here.",
  },
  {
    name: "Industrial Tribunal",
    forumType: "tribunal",
    level: "state",
    description: "Collective/industrial disputes -- retrenchment, closure, collective bargaining disputes, larger-scale industrial matters.",
    pecuniaryMin: null,
    pecuniaryMax: null,
    subjectTags: ["industrial dispute", "retrenchment", "closure", "collective bargaining", "strike"],
    caseTypeTags: ["labour"],
    appealsTo: "High Court",
    notes: "",
  },
  {
    name: "Central Administrative Tribunal (CAT)",
    forumType: "tribunal",
    level: "national",
    description: "Service matters of central government employees -- recruitment, promotion, disciplinary action, pension.",
    pecuniaryMin: null,
    pecuniaryMax: null,
    subjectTags: ["service matter", "government employee", "recruitment", "disciplinary action", "pension", "promotion"],
    caseTypeTags: ["administrative"],
    appealsTo: "High Court",
    notes: "Has benches across states -- file at the bench with jurisdiction over the relevant government office.",
  },
  {
    name: "Debt Recovery Tribunal (DRT)",
    forumType: "tribunal",
    level: "state",
    description: "Recovery of debts owed to banks/financial institutions above the statutory threshold.",
    pecuniaryMin: 2000000,
    pecuniaryMax: null,
    subjectTags: ["bank loan recovery", "npa", "debt", "sarfaesi"],
    caseTypeTags: ["civil"],
    appealsTo: "Debt Recovery Appellate Tribunal",
    notes: "Threshold (commonly cited around ₹20 lakh) is set by the Recovery of Debts and Bankruptcy Act and can change by amendment -- verify the current figure.",
  },
  {
    name: "Income Tax Appellate Tribunal (ITAT)",
    forumType: "tribunal",
    level: "state",
    description: "Appeals against orders of income tax authorities (Commissioner of Income Tax (Appeals)).",
    pecuniaryMin: null,
    pecuniaryMax: null,
    subjectTags: ["income tax", "tax assessment", "appeal", "tax dispute"],
    caseTypeTags: ["tax"],
    appealsTo: "High Court",
    notes: "",
  },
  {
    name: "National Company Law Tribunal (NCLT)",
    forumType: "tribunal",
    level: "state",
    description: "Company law and insolvency matters -- oppression/mismanagement, insolvency resolution (IBC), company disputes.",
    pecuniaryMin: null,
    pecuniaryMax: null,
    subjectTags: ["company law", "insolvency", "ibc", "oppression mismanagement", "corporate dispute"],
    caseTypeTags: ["civil", "administrative"],
    appealsTo: "National Company Law Appellate Tribunal (NCLAT)",
    notes: "Has benches across states -- file at the bench with jurisdiction over the company's registered office.",
  },
  {
    name: "National Green Tribunal (NGT)",
    forumType: "tribunal",
    level: "national",
    description: "Environmental disputes -- pollution, forest and environmental clearance violations, compensation for environmental damage.",
    pecuniaryMin: null,
    pecuniaryMax: null,
    subjectTags: ["environment", "pollution", "forest", "environmental clearance", "ecology"],
    caseTypeTags: ["administrative", "civil"],
    appealsTo: "Supreme Court of India",
    notes: "Has a principal bench and zonal benches -- file at the zonal bench with jurisdiction over the affected area.",
  },
  {
    name: "Motor Accidents Claims Tribunal (MACT)",
    forumType: "tribunal",
    level: "district",
    description: "Compensation claims arising from motor vehicle accidents -- injury, death, or property damage.",
    pecuniaryMin: null,
    pecuniaryMax: null,
    subjectTags: ["motor accident", "compensation", "injury claim", "accident claim"],
    caseTypeTags: ["civil"],
    appealsTo: "High Court",
    notes: "",
  },
  {
    name: "Rent Control Court / Rent Authority",
    forumType: "civil_court",
    level: "district",
    description: "Landlord-tenant disputes -- eviction, rent fixation, tenancy renewal, under the applicable state rent control law.",
    pecuniaryMin: null,
    pecuniaryMax: null,
    subjectTags: ["rent", "eviction", "tenancy", "landlord", "tenant"],
    caseTypeTags: ["civil"],
    appealsTo: "District Court / High Court",
    notes: "Rent control law, and whether a dedicated Rent Authority even exists, varies significantly by state -- verify locally.",
  },
  {
    name: "High Court (Writ Jurisdiction)",
    forumType: "high_court",
    level: "state",
    description: "Constitutional writs (habeas corpus, mandamus, certiorari, prohibition, quo warranto) for enforcement of fundamental rights or against government/authority action; also hears civil, criminal, and other appeals.",
    pecuniaryMin: null,
    pecuniaryMax: null,
    subjectTags: ["fundamental rights", "writ", "habeas corpus", "mandamus", "certiorari", "government action", "appeal"],
    caseTypeTags: ["writ", "administrative", "civil", "criminal"],
    appealsTo: "Supreme Court of India",
    notes: "",
  },
  {
    name: "Supreme Court of India",
    forumType: "supreme_court",
    level: "national",
    description: "Apex constitutional court -- final appeals, Special Leave Petitions, and writs under Article 32 for enforcement of fundamental rights.",
    pecuniaryMin: null,
    pecuniaryMax: null,
    subjectTags: ["fundamental rights", "constitutional", "special leave petition", "final appeal"],
    caseTypeTags: ["writ", "civil", "criminal", "administrative"],
    appealsTo: null,
    notes: "Ordinarily approached only after exhausting the High Court, except for a direct Article 32 writ petition.",
  },
  {
    name: "Arbitral Tribunal (private arbitration)",
    forumType: "arbitration",
    level: "national",
    description: "Private dispute resolution under an arbitration clause/agreement, governed by the Arbitration and Conciliation Act, 1996 -- not a government court.",
    pecuniaryMin: null,
    pecuniaryMax: null,
    subjectTags: ["arbitration", "contract dispute", "commercial dispute", "arbitration clause"],
    caseTypeTags: ["arbitration"],
    appealsTo: "Court under Section 34 (limited grounds to set aside an award)",
    notes: "Only available where the parties have an arbitration agreement/clause -- cannot be unilaterally invoked otherwise.",
  },
  {
    name: "Police Station (FIR / Complaint)",
    forumType: "police",
    level: "local",
    description: "Not an adjudicating forum -- the administrative starting point for a criminal matter: registering an FIR or a non-cognizable complaint.",
    pecuniaryMin: null,
    pecuniaryMax: null,
    subjectTags: ["fir", "cognizable offence", "criminal complaint", "police complaint"],
    caseTypeTags: ["criminal"],
    appealsTo: "Judicial Magistrate (if a valid FIR is refused, a complaint can be made to the Magistrate instead)",
    notes: "",
  },
  {
    name: "Gram Nyayalaya",
    forumType: "other",
    level: "local",
    description: "Village/taluk-level court for petty civil and criminal matters, offering faster, informal, local access to justice.",
    pecuniaryMin: null,
    pecuniaryMax: null,
    subjectTags: ["petty civil dispute", "petty criminal offence", "village dispute", "local dispute"],
    caseTypeTags: ["civil", "criminal"],
    appealsTo: "Sessions Court / District Court",
    notes: "Not yet established in every state/district -- check whether one is functional in the relevant area.",
  },
  {
    name: "Cooperative Court / Registrar of Cooperative Societies",
    forumType: "tribunal",
    level: "state",
    description: "Disputes concerning cooperative societies -- membership, management, and internal disputes under the applicable state Cooperative Societies Act.",
    pecuniaryMin: null,
    pecuniaryMax: null,
    subjectTags: ["cooperative society", "membership dispute", "society management"],
    caseTypeTags: ["civil", "administrative"],
    appealsTo: "State Cooperative Tribunal / High Court",
    notes: "Structure and naming varies by state's own Cooperative Societies Act.",
  },
];
