"use client";

import { useEffect, useState } from "react";
import CollapsibleSection from "../../components/CollapsibleSection.jsx";

const TIER_LABEL = { ncert: "NCERT", official: "Official", newspaper: "Newspaper", private_vendor: "Vendor" };

// Bloom Knowledge Forest (lib/forest/growth.js's HEALTH_STATES) -- same
// tooltip labels as the Papers page's health dot.
const HEALTH_LABEL = { dormant: "Dormant", bare: "Bare branches", falling: "Falling leaves", yellow: "Yellow leaves", healthy: "Healthy" };

// Piece C of the "1-year strategy" request: GS content grouped by theme
// (Polity, Governance, International Relations, ... -- each subtopic's own
// `section` field, see lib/subjects/themeGuide.js) with where-to-start,
// sources-to-follow, and what-to-include-in-notes per theme. Everything here
// is reused from data already tracked per subtopic -- nothing is freshly
// AI-generated by this page.
export default function GuidePage() {
  const [data, setData] = useState(null);
  const [error, setError] = useState(null);

  useEffect(() => {
    fetch("/api/theme-guide")
      .then((r) => r.json())
      .then((d) => {
        if (d.error) setError(d.error);
        else setData(d);
      })
      .catch((e) => setError(e.message));
  }, []);

  if (error === "onboarding_not_complete") {
    return (
      <>
        <h1>Subject-wise guide</h1>
        <div className="card">
          <p className="lede" style={{ marginBottom: 10 }}>
            Set up your plan first — pick your 2 starting GS papers and your optional subject.
          </p>
          <a className="btn btn-primary" href="/onboarding">
            Get started →
          </a>
        </div>
      </>
    );
  }

  if (error) {
    return (
      <>
        <h1>Subject-wise guide</h1>
        <div className="error-box">{error}</div>
      </>
    );
  }

  if (!data) return <div className="loading">Loading…</div>;

  return (
    <>
      <h1>Subject-wise guide</h1>
      <p className="lede">
        Your unlocked GS papers, broken down by theme — Polity, Governance, International Relations, and more as
        more GS papers unlock. Where to start, which sources to follow, and what to include in notes, all built from
        your own tracked data (difficulty, PYQ frequency, sources you've registered, notes already generated).{" "}
        <a href="/notes/export">Export a printable revision booklet →</a> ·{" "}
        <a href="/reference">Search your reference sources →</a>
      </p>

      {data.themes.length === 0 && (
        <div className="card">
          <p className="lede" style={{ marginBottom: 0 }}>
            No content loaded yet in your unlocked GS papers. Check back once content has been added.
          </p>
        </div>
      )}

      {data.themes.map((t, idx) => (
        <CollapsibleSection
          title={t.theme}
          meta={`${t.subjectDisplayName} · ${t.subtopicCount} topics · ${Math.round(t.avgMastery * 100)}% mastery`}
          defaultOpen={idx === 0}
          key={t.theme}
        >
          <h3 style={{ fontSize: 13.5, marginBottom: 6 }}>Where to start</h3>
          <ol style={{ margin: "0 0 14px", paddingLeft: 20, fontSize: 13.5 }}>
            {t.startHere.map((s) => (
              <li key={s.id} style={{ marginBottom: 4 }}>
                <span
                  className={`mastery-health-dot mastery-health-${s.health}`}
                  title={`Retention: ${HEALTH_LABEL[s.health] ?? s.health} -- fades over time since your last attempt, revisit to keep it up`}
                  style={{ marginRight: 6 }}
                />
                <a href={`/learn/${s.id}`}>{s.topicText}</a>
              </li>
            ))}
          </ol>
          {t.subtopicCount > t.startHere.length && (
            <p style={{ fontSize: 12, color: "var(--ink-soft)", marginTop: -10, marginBottom: 14 }}>
              +{t.subtopicCount - t.startHere.length} more topics in this theme.
            </p>
          )}

          <h3 style={{ fontSize: 13.5, marginBottom: 6 }}>Sources to follow</h3>
          {t.sourcesToFollow.length === 0 ? (
            <p style={{ fontSize: 12.5, color: "var(--ink-soft)", marginBottom: 14 }}>No sources registered yet for this theme.</p>
          ) : (
            <ul style={{ margin: "0 0 14px", paddingLeft: 20, fontSize: 13.5 }}>
              {t.sourcesToFollow.map((s, i) => (
                <li key={i} style={{ marginBottom: 4 }}>
                  {s.url.startsWith("storage://") ? s.title : <a href={s.url} target="_blank" rel="noreferrer">{s.title}</a>}
                  {s.sourceTier && <span className="qualifying-pill" style={{ marginLeft: 6 }}>{TIER_LABEL[s.sourceTier] ?? s.sourceTier}</span>}
                </li>
              ))}
            </ul>
          )}

          <h3 style={{ fontSize: 13.5, marginBottom: 6 }}>What to include in notes</h3>
          {t.notesToInclude.length === 0 ? (
            <p style={{ fontSize: 12.5, color: "var(--ink-soft)", marginBottom: 0 }}>
              Nothing generated yet — visit Teach on a topic above first, and its key points will show up here.
            </p>
          ) : (
            <ul style={{ margin: 0, paddingLeft: 20, fontSize: 13.5 }}>
              {t.notesToInclude.map((n, i) => (
                <li key={i} style={{ marginBottom: 3 }}>
                  {n}
                </li>
              ))}
            </ul>
          )}
        </CollapsibleSection>
      ))}
    </>
  );
}
